version: '3'

services:
  api:
    build: ./api
    ports:
      - 5555:5000
  frontend:
    build: ./frontend
    ports:
      - 3333:3000
  mysql:
    image: mysql
  adminer:
    image: adminer
    ports:
      - 8888:8080
